// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFb-G0zBinGrnkmYUASb4YQjJZyZElQdM',
    appId: '1:416073218612:web:b13d267f80a232c2bf2861',
    messagingSenderId: '416073218612',
    projectId: 'food-runner-restaurant',
    authDomain: 'food-runner-restaurant.firebaseapp.com',
    storageBucket: 'food-runner-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTjLgrJj4isMmYvJ5kavFAuHpJcZcX3E',
    appId: '1:416073218612:android:ec70019f18bc8f1abf2861',
    messagingSenderId: '416073218612',
    projectId: 'food-runner-restaurant',
    storageBucket: 'food-runner-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvemA1_PPti9ykSqKr1gRFVUDEc1qZu74',
    appId: '1:416073218612:ios:521cc6e83d145e83bf2861',
    messagingSenderId: '416073218612',
    projectId: 'food-runner-restaurant',
    storageBucket: 'food-runner-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.foodRunnerRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvemA1_PPti9ykSqKr1gRFVUDEc1qZu74',
    appId: '1:416073218612:ios:521cc6e83d145e83bf2861',
    messagingSenderId: '416073218612',
    projectId: 'food-runner-restaurant',
    storageBucket: 'food-runner-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.foodRunnerRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFb-G0zBinGrnkmYUASb4YQjJZyZElQdM',
    appId: '1:416073218612:web:70345976f4ac8a76bf2861',
    messagingSenderId: '416073218612',
    projectId: 'food-runner-restaurant',
    authDomain: 'food-runner-restaurant.firebaseapp.com',
    storageBucket: 'food-runner-restaurant.firebasestorage.app',
  );
}
